### ISSUE TITLE
A scary amount of unit tests fails for me on Linux

### ISSUE THREAD

**Issue by Mailaender** [cdhowie/Eluant#5] opened 2015-02-01 13:30 UTC
![image](https://cloud.githubusercontent.com/assets/756669/5992191/cb33b628-aa1e-11e4-80aa-82ce09105a7d.png)

**Comment by cdhowie** [comment] 2015-02-02 17:43
Cannot reproduce.

Which version of Lua are you using?

**Comment by Mailaender** [comment] 2015-02-02 20:02
https://software.opensuse.org/package/lua51

**Comment by cdhowie** [comment] 2015-02-03 17:01
I assume then that you are using openSUSE 13.2?  What architecture?

Which version of Mono?

(I am going to attempt to build a VM to match your system and see if I can reproduce there.)

**Comment by Mailaender** [comment] 2015-02-03 19:47
openSUSE 13.2 with Mono 3.10 (from Mono:Factory). Lua 5.2 is also installed.

**Comment by cdhowie** [comment] 2015-02-03 20:42
Again, what architecture?  (32 or 64 bit OS?)

**Comment by Mailaender** [comment] 2015-02-03 20:48
64-bit OS, sorry.

**Comment by cdhowie** [comment] 2015-02-04 18:06
Cannot reproduce in this environment.

```
> uname -a
Linux linux-kzy5 3.16.6-2-desktop #1 SMP PREEMPT Mon Oct 20 13:47:22 UTC 2014 (feb42ea) x86_64 x86_64 x86_64 GNU/Linux
> rpm -q mono-devel lua51-devel
mono-devel-3.8.0-1.4.x86_64
lua51-devel-5.1.5-10.2.2.x86_64
> git rev-parse HEAD
1c4a1f0e584afc59231b403b0f87b7dbc7575293
> nunit-console4 Eluant.Tests.dll
NUnit version 2.4.8
Copyright (C) 2002-2007 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment - 
   OS Version: Unix 3.16.6.2
  CLR Version: 4.0.30319.17020 ( 3.8.0 (tarball Fri Oct 10 15:00:11 UTC 2014) )

..................[LuaClrObjectReference ClrObject:Eluant.Tests.Types+MathBindingObject]
...........
Tests run: 29, Failures: 0, Not run: 0, Time: 0.429 seconds
```

There is also something fishy going on with the numbers; according to your screenshot you ran 30 tests, but there are only 29 in the Eluant test suite.

**Comment by Mailaender** [comment] 2015-02-04 19:30
I am testing https://github.com/cdhowie/Eluant/pull/4:

```
matthias@linux-at2i:~/Entwicklung/Eluant/Eluant.Tests/bin/Debug> uname -a
Linux linux-at2i.site 3.16.7-7-desktop #1 SMP PREEMPT Wed Dec 17 18:00:44 UTC 2014 (762f27a) x86_64 x86_64 x86_64 GNU/Linux
```

```
matthias@linux-at2i:~/Entwicklung/Eluant/Eluant.Tests/bin/Debug> rpm -q mono-core lua51
mono-core-3.10.0-148.1.x86_64
lua51-5.1.5-10.2.2.x86_64
```

```
matthias@linux-at2i:~/Entwicklung/Eluant/Eluant.Tests/bin/Debug>  nunit-console4 Eluant.Tests.dll
NUnit version 2.4.8
Copyright (C) 2002-2007 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment - 
   OS Version: Unix 3.16.7.7
  CLR Version: 4.0.30319.17020 ( 3.10.0 (tarball Thu Nov 13 19:56:43 UTC 2014) )

.F..F...F......F.....F.[LuaFunction]
..F......F.F.F.
Tests run: 29, Failures: 9, Not run: 0, Time: 0.518 seconds

Test Case Failures:
1) Eluant.Tests.Functions.BasicFunction :   result.Count
  Expected: 1
  But was:  2

at Eluant.Tests.Functions.BasicFunction () [0x00060] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Functions.cs:44
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

2) Eluant.Tests.Functions.CallbackOnCoroutineFails :   Call succeeded.
  Expected: False
  But was:  True

at Eluant.Tests.Functions.CallbackOnCoroutineFails () [0x00074] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Functions.cs:164
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

3) Eluant.Tests.Functions.HugeResultList : System.InvalidOperationException : Nullable object must have a value.
at System.Nullable`1[System.Double].get_Value () [0x00016] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System/Nullable.cs:107
at Eluant.Tests.Functions.<HugeResultList>m__2 (Eluant.LuaValue i) [0x00009] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Functions.cs:150
at System.Linq.Enumerable+<CreateSelectIterator>c__Iterator10`2[Eluant.LuaValue,System.Int32].MoveNext () [0x00059] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/System.Core/System.Linq/Enumerable.cs:2270
at System.Linq.Enumerable.Sum (IEnumerable`1 source) [0x0001b] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/System.Core/System.Linq/Enumerable.cs:2535
at Eluant.Tests.Functions.HugeResultList () [0x0009b] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Functions.cs:150
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

4) Eluant.Tests.Runtime.LuaCollectsObjectsAfterReferencesAreDisposed :   Expected: 33199
  But was:  33279

at Eluant.Tests.Runtime.LuaCollectsObjectsAfterReferencesAreDisposed () [0x00141] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Runtime.cs:63
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

5) Eluant.Tests.TransparentBinding.Basic : System.InvalidCastException : Cannot cast from source type to destination type.
at Eluant.Tests.TransparentBinding.Basic () [0x00042] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/TransparentBinding.cs:80
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

6) Eluant.Tests.Types.DifferentReferencesToSameClrObjectAreUnequal :   r.Count
  Expected: 1
  But was:  2

at Eluant.Tests.Types.DifferentReferencesToSameClrObjectAreUnequal () [0x00065] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Types.cs:141
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

7) Eluant.Tests.Types.Table :   results.Count
  Expected: 1
  But was:  2

at Eluant.Tests.Types.Table () [0x0006c] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Types.cs:123
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

8) Eluant.Tests.Types.TransparentBinding : System.InvalidCastException : Cannot cast from source type to destination type.
at Eluant.Tests.Types.TransparentBinding () [0x00050] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Types.cs:246
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

9) Eluant.Tests.Types.TransparentObjectEquality : System.InvalidCastException : Cannot cast from source type to destination type.
at Eluant.Tests.Types.TransparentObjectEquality () [0x00057] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Types.cs:302
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230
```

**Comment by cdhowie** [comment] 2015-02-04 21:04
I updated Mono to 3.12.0 from Mono:Factory (3.10.0 is no longer available) and still cannot reproduce.

Please show the output of the following commands from within `Eluant.Tests/bin/Debug`:

```
git rev-parse HEAD
git status
MONO_LOG_LEVEL="debug" MONO_LOG_MASK="dll" nunit-console4 Eluant.Tests.dll
```

**Comment by Mailaender** [comment] 2015-02-05 20:35
```
git rev-parse HEAD
19d264267444a231d2f3045ef703be3ce2b1cbe7
```

```
git status
Auf Branch master
Ihr Branch ist auf dem selben Stand wie 'origin/master'.
nichts zu committen, Arbeitsverzeichnis unverändert
```

```
MONO_LOG_LEVEL="debug" MONO_LOG_MASK="dll" nunit-console4 Eluant.Tests.dll
NUnit version 2.4.8
Copyright (C) 2002-2007 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment - 
   OS Version: Unix 3.16.7.7
  CLR Version: 4.0.30319.17020 ( 3.10.0 (tarball Thu Nov 13 19:56:43 UTC 2014) )

.Mono: DllImport attempting to load: 'liblua5.1.so.0'.
Mono: DllImport error loading library '/tmp/nunit20/ShadowCopyCache/5875_635587688291123210/Tests/assembly/shadow/abfe700f/30160400_9be8740f_00000001/liblua5.1.so.0': '/tmp/nunit20/ShadowCopyCache/5875_635587688291123210/Tests/assembly/shadow/abfe700f/30160400_9be8740f_00000001/liblua5.1.so.0: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/tmp/nunit20/ShadowCopyCache/5875_635587688291123210/Tests/assembly/shadow/abfe700f/30160400_9be8740f_00000001/liblua5.1.so.0.so': '/tmp/nunit20/ShadowCopyCache/5875_635587688291123210/Tests/assembly/shadow/abfe700f/30160400_9be8740f_00000001/liblua5.1.so.0.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport loaded library 'liblua5.1.so.0'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_newstate'.
Mono: Probing 'lua_newstate'.
Mono: Found as 'lua_newstate'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'luaL_newstate'.
Mono: Probing 'luaL_newstate'.
Mono: Found as 'luaL_newstate'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_createtable'.
Mono: Probing 'lua_createtable'.
Mono: Found as 'lua_createtable'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_setfield'.
Mono: Probing 'lua_setfield'.
Mono: Found as 'lua_setfield'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'luaL_openlibs'.
Mono: Probing 'luaL_openlibs'.
Mono: Found as 'luaL_openlibs'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_pushlightuserdata'.
Mono: Probing 'lua_pushlightuserdata'.
Mono: Found as 'lua_pushlightuserdata'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'luaL_newmetatable'.
Mono: Probing 'luaL_newmetatable'.
Mono: Found as 'luaL_newmetatable'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_pushcclosure'.
Mono: Probing 'lua_pushcclosure'.
Mono: Found as 'lua_pushcclosure'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_settable'.
Mono: Probing 'lua_settable'.
Mono: Found as 'lua_settable'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_pushboolean'.
Mono: Probing 'lua_pushboolean'.
Mono: Found as 'lua_pushboolean'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_settop'.
Mono: Probing 'lua_settop'.
Mono: Found as 'lua_settop'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_pushnil'.
Mono: Probing 'lua_pushnil'.
Mono: Found as 'lua_pushnil'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_pushlstring'.
Mono: Probing 'lua_pushlstring'.
Mono: Found as 'lua_pushlstring'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_newuserdata'.
Mono: Probing 'lua_newuserdata'.
Mono: Found as 'lua_newuserdata'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'luaL_loadbuffer'.
Mono: Probing 'luaL_loadbuffer'.
Mono: Found as 'luaL_loadbuffer'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_gettop'.
Mono: Probing 'lua_gettop'.
Mono: Found as 'lua_gettop'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_checkstack'.
Mono: Probing 'lua_checkstack'.
Mono: Found as 'lua_checkstack'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_getfield'.
Mono: Probing 'lua_getfield'.
Mono: Found as 'lua_getfield'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_remove'.
Mono: Probing 'lua_remove'.
Mono: Found as 'lua_remove'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_insert'.
Mono: Probing 'lua_insert'.
Mono: Found as 'lua_insert'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_pcall'.
Mono: Probing 'lua_pcall'.
Mono: Found as 'lua_pcall'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_type'.
Mono: Probing 'lua_type'.
Mono: Found as 'lua_type'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_toboolean'.
Mono: Probing 'lua_toboolean'.
Mono: Found as 'lua_toboolean'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_tonumber'.
Mono: Probing 'lua_tonumber'.
Mono: Found as 'lua_tonumber'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_pushvalue'.
Mono: Probing 'lua_pushvalue'.
Mono: Found as 'lua_pushvalue'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_rawseti'.
Mono: Probing 'lua_rawseti'.
Mono: Found as 'lua_rawseti'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_rawgeti'.
Mono: Probing 'lua_rawgeti'.
Mono: Found as 'lua_rawgeti'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_gettable'.
Mono: Probing 'lua_gettable'.
Mono: Found as 'lua_gettable'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_setmetatable'.
Mono: Probing 'lua_setmetatable'.
Mono: Found as 'lua_setmetatable'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_pushnumber'.
Mono: Probing 'lua_pushnumber'.
Mono: Found as 'lua_pushnumber'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_close'.
Mono: Probing 'lua_close'.
Mono: Found as 'lua_close'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_touserdata'.
Mono: Probing 'lua_touserdata'.
Mono: Found as 'lua_touserdata'.
Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_getmetatable'.
Mono: Probing 'lua_getmetatable'.
Mono: Found as 'lua_getmetatable'.
F..Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_tolstring'.
Mono: Probing 'lua_tolstring'.
Mono: Found as 'lua_tolstring'.
F...F......Mono: DllImport searching in: 'liblua5.1.so.0' ('liblua5.1.so.0').
Mono: Searching for 'lua_next'.
Mono: Probing 'lua_next'.
Mono: Found as 'lua_next'.
F.....F.[LuaFunction]
..F......F.F.F.
Tests run: 29, Failures: 9, Not run: 0, Time: 0.504 seconds

Test Case Failures:
1) Eluant.Tests.Functions.BasicFunction :   result.Count
  Expected: 1
  But was:  2

at Eluant.Tests.Functions.BasicFunction () [0x00060] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Functions.cs:44
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

2) Eluant.Tests.Functions.CallbackOnCoroutineFails :   Call succeeded.
  Expected: False
  But was:  True

at Eluant.Tests.Functions.CallbackOnCoroutineFails () [0x00074] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Functions.cs:164
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

3) Eluant.Tests.Functions.HugeResultList : System.InvalidOperationException : Nullable object must have a value.
at System.Nullable`1[System.Double].get_Value () [0x00016] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System/Nullable.cs:107
at Eluant.Tests.Functions.<HugeResultList>m__2 (Eluant.LuaValue i) [0x00009] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Functions.cs:150
at System.Linq.Enumerable+<CreateSelectIterator>c__Iterator10`2[Eluant.LuaValue,System.Int32].MoveNext () [0x00059] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/System.Core/System.Linq/Enumerable.cs:2270
at System.Linq.Enumerable.Sum (IEnumerable`1 source) [0x0001b] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/System.Core/System.Linq/Enumerable.cs:2535
at Eluant.Tests.Functions.HugeResultList () [0x0009b] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Functions.cs:150
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

4) Eluant.Tests.Runtime.LuaCollectsObjectsAfterReferencesAreDisposed :   Expected: 33199
  But was:  33279

at Eluant.Tests.Runtime.LuaCollectsObjectsAfterReferencesAreDisposed () [0x00141] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Runtime.cs:63
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

5) Eluant.Tests.TransparentBinding.Basic : System.InvalidCastException : Cannot cast from source type to destination type.
at Eluant.Tests.TransparentBinding.Basic () [0x00042] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/TransparentBinding.cs:80
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

6) Eluant.Tests.Types.DifferentReferencesToSameClrObjectAreUnequal :   r.Count
  Expected: 1
  But was:  2

at Eluant.Tests.Types.DifferentReferencesToSameClrObjectAreUnequal () [0x00065] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Types.cs:141
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

7) Eluant.Tests.Types.Table :   results.Count
  Expected: 1
  But was:  2

at Eluant.Tests.Types.Table () [0x0006c] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Types.cs:123
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

8) Eluant.Tests.Types.TransparentBinding : System.InvalidCastException : Cannot cast from source type to destination type.
at Eluant.Tests.Types.TransparentBinding () [0x00050] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Types.cs:246
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

9) Eluant.Tests.Types.TransparentObjectEquality : System.InvalidCastException : Cannot cast from source type to destination type.
at Eluant.Tests.Types.TransparentObjectEquality () [0x00057] in /home/matthias/Entwicklung/Eluant/Eluant.Tests/Types.cs:302
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/abuild/rpmbuild/BUILD/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230
```

**Comment by cdhowie** [comment] 2015-02-05 21:46
The commit you are on does not exist in my repository, but it does in yours.

Please try checking out commit 1c4a1f0e584afc59231b403b0f87b7dbc7575293, rebuilding, and re-running the unit tests.  If the issue goes away then the bug was introduced in your fork of Eluant.

**Comment by cdhowie** [comment] 2015-02-10 17:55
Closing as invalid since the commit used to build doesn't exist in this repository.  If you can reproduce the failures on the latest master commit in this repository then feel free to comment and we can re-open, but it's not feasible for me to handle bugs introduced in forks not under my control.

**Closed as completed by cdhowie** 2015-02-10 17:55 UTC
Labels: bug, invalid
